#!/usr/bin/env lua
prog = {
  name = "skypelog",
  banner = "skypelog © Reuben Thomas (rrt@sc3d.org)",
  purpose = "Dump a Skype chat log",
}

require "std"
require "skypelog"
require "json"

-- Main routine
getopt.processArgs ()
if #arg == 0 then
  getopt.usage ()
  os.exit (1)
end
io.processFiles (function (file)
                   print (json.encode (skypelog.parse_old (file)))
                 end)
